color0 #141317
color1 #ffb4ab
color2 #cdbdff
color3 #cbc2e3
color4 #ffaedc
color5 #cdbdff
color6 #cbc2e3
color7 #e6e1e7
color8 #938f9b
color9 #ffb4ab
color10 #cdbdff
color11 #cbc2e3
color12 #ffaedc
color13 #cdbdff
color14 #cbc2e3
color15 #e6e1e7

cursor                #e6e1e7
cursor_text_color     #141317
background            #141317
foreground            #e6e1e7
selection_foreground  #cac4d1
selection_background  #484550
active_border_color   #cdbdff
inactive_border_color #484550
url_color             #cdbdff
